name: Validate Dependency Check (Ubuntu Latest)

on:
  workflow_dispatch:
  push:

jobs:
  validate:
    name: Run Dependency Check on ubuntu-latest
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show architecture
        run: uname -m

      # - name: Install and setup Podman
      #   run: |
      #     brew install podman
      #     podman machine init || true
      #     podman machine start
      #     podman info

      - name: Login to GHCR with Podman
        run: |
          podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ inputs.token }}

      - name: Create dummy Node project
        run: |
          mkdir nodeapp
          cd nodeapp
          npm init -y
          echo "console.log('Hello');" > index.js

      - name: Run Dependency Check from GHCR
        run: |
          mkdir -p reports
          podman run --rm -v $PWD:/src ghcr.io/poorneshorg/dependency-check:multiarch \
            --project "GHCR-UbuntuLatest" \
            --scan /src/nodeapp \
            --format HTML \
            --out /src/reports

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report-ubuntu-latest
          path: reports/
